name:                bookmarkext
version:             0.1.0.0
github:              "odrnk/bookmarkext"
license:             GPL-3
author:              "Anonymous"

# Metadata used when publishing your package
synopsis:            Browser extension of bookmark system
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on Github at <https://github.com/odrnk/bookmarkext#readme>

dependencies:
- base >= 4.7 && < 5
- postgresql-simple
- uuid
- time
- aeson
- configurator
- text
- bytestring
- transformers
- websockets
- wai
- wai-websockets
- warp
- http-types

library:
  source-dirs: src

executables:
  bookmarkext-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - bookmarkext

tests:
  bookmarkext-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - bookmarkext
